# Generated by Django 5.2.6 on 2025-11-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alumni_connection_event_eventregistration_jobposting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
